# Generated by Django 3.2.5 on 2021-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='aslkdjfklj'),
            preserve_default=False,
        ),
    ]
