# Generated by Django 3.2.5 on 2021-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210724_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
