# Generated by Django 3.2.5 on 2021-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
